### ISSUE TITLE
Unrecognized variable 'full_deduced_net'.

### ISSUE THREAD

**Issue by Alessi0X** [jamesjcai/SBEToolbox_lite#1]
Dear James,
I came across two minor bugs in function `sbe_module.m`.

(1) Line 22: `g = mcl(sbeG, 2, 2, 0, false);`
The last input argument to `mcl()` (i.e., the number of iterations) is missing and the code errors.

(2) Line 29: `moduleid=zeros(1,size(full_deduced_net, 1));`
Variable `full_deduced_net ` is used, but not declared and the code errors.

A workaround for (1) is to change 
`g = mcl(sbeG, 2, 2, 0, false);`
to
`g = mcl(sbeG, 2, 2, 0, false, 20);`
since 20 is the default number of iterations in `mcl`.

Best,
Alessio

**Comment by jamesjcai** [comment]
Just fixed the two places accordingly. Please let me know if it works now. Thank you!

**Comment by alessi0x** [comment]
Hi James,
perfectly fixed. Thanks.

You may now close the issue, if you prefer to.
